source "https://rubygems.org"

gem "jekyll", "~> 3.9.5"
gem "jekyll-remote-theme"
gem "jekyll-include-cache"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "rubyzip", "~> 2.3"
gem "base64"
gem "bigdecimal"
gem "csv"
gem "webrick"
gem "kramdown-parser-gfm"
